# Github Actions에 표시될 이름
name: FMD-CI/CD

# Event Trigger
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-common.yaml
        run: |
          cd ./src/main/resources
          touch ./application-common.yaml
          echo "${{ secrets.APPLICATION_COMMON}}" > ./application-common.yaml

      - name: make application-oauth.yaml
        run: |
          cd ./src/main/resources
          touch ./application-oauth.yaml
          echo "${{ secrets.APPLICATION_OAUTH}}" > ./application-oauth.yaml

      - name: make application-prod.yaml
        if: contains(github.ref, 'main')
        run: |
          cd ./src/main/resources
          touch ./application-prod.yaml
          echo "${{ secrets.APPLICATION_PROD}}" > ./application-prod.yaml

      - name: make application-dev.yaml
        if: contains(github.ref, 'develop')
        run: |
          cd ./src/main/resources
          touch ./application-dev.yaml
          echo "${{ secrets.APPLICATION_DEV}}" > ./application-dev.yaml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod -t ${{ secrets.DOCKER_USERNAME }}/fmd-prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/fmd-prod

      - name: Docker build & push to dev
        if: contains(github.ref, 'develop')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/fmd-dev:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fmd-dev:latest

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker-compose -f docker-compose.prod.yaml down --rmi all 
            docker pull ${{ secrets.DOCKER_USERNAME }}/fmd-prod:latest
            docker-compose -f docker-compose.prod.yaml up -d
            docker rmi $(docker images -f "dangling=true" -q)

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        if: contains(github.ref, 'develop')
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker-compose -f docker-compose.dev.yaml down --rmi all
            docker pull ${{ secrets.DOCKER_USERNAME }}/fmd-dev:latest
            docker-compose -f docker-compose.dev.yaml up -d
            docker rmi $(docker images -f "dangling=true" -q)
